### ISSUE TITLE
Correctly handle hardware / native cursors in anvil

### ISSUE THREAD

**Issue by vberger** [Smithay/smithay#119]
Currently, when an alternate client-provided cursor is drawn in anvil, the original cursor (be it the native cursor on the winit backend, or the hardware cursor on a tty) is not hidden.

**Comment by YaLTeR** [comment]
Would it make sense to forward the client cursor up to the winit backend or to the hardware cursor instead of hiding? I don't know how cursors work so maybe they don't work like that.

**Comment by vberger** [comment]
I don't think winit allows to change the cursor arbitrarily, so we may be out of luck for this one. Maybe we could still do that for the hardware cursor though.

**Comment by Drakulix** [comment]
> Would it make sense to forward the client cursor up to the winit backend or to the hardware cursor instead of hiding? I don't know how cursors work so maybe they don't work like that.

Yes. For winit we cannot easily do this (using wayland-client we could), but for hardware cursors that is the goal.
However for this to work, we would need to render to the cursor plane or scan-out the cursor buffer directly. Neither is easily possible with the current api. So I would post-pone this until another renderer-rework.

The rendering issue however is not fixed with #221, so I am going to close this.
