### ISSUE TITLE
NVIDIA Driver Support

### ISSUE THREAD

**Issue by skyne98** [Smithay/smithay#128]
Hey there! As we had a small discussion on the twitter before, this should be a good place for its continuation.

The point of the discussion is: can we have NVIDIA Linux driver support? As far as I know, the problem is in the way NVIDIA allocates and manages memory (using EGLStreams), which is not compatible with the Wayland way of doing things.

Neither Gnome, nor KDE support Wayland on NVIDIA. However, as @levansfr and @Drakulix mentioned on twitter, it is a possibility in Smithay - which is exciting.

**Comment by Drakulix** [comment]
Yeah this is entirely possible, I already have a bunch of code regarding that on my hard drive, I just need to find the time to test, debug and polish it. So this will happen rather sooner then later actually.

>  which is not compatible with the Wayland way of doing things.
It is, it is just annoying to support two different code paths.

> Neither Gnome, nor KDE support Wayland on NVIDIA.
Gnome is actually [actively working](https://www.phoronix.com/scan.php?page=news_item&px=GNOME-Mutter-Mainline-EGLStream) on support btw, not sure what the story for KDE is though.

**Comment by skyne98** [comment]
@Drakulix, glad to hear the news. I will be very excited to hear about the status of this feature :+1:

**Comment by csnewman** [comment]
@Drakulix Did you ever get chance to create a PR for this?

**Comment by Drakulix** [comment]
> @Drakulix Did you ever get chance to create a PR for this?

I have an implementation that *should* be working, but errors out, because my nvidia card does not expose `crtc`'s for EGLStreams, but only planes. Smithay on the other hand has no idea what drm-planes are and any work-around would have been quite hacky.

It might be, that some older cards work with my implementation, but I have no way to tell, so I have not released it.

Regarding planes in smithay: Planes are not terribly useful without the atomic mode-setting api of the drm system, so I do not want to add support for those for smithay's current renderer, but rather when adding atomic-modesetting support. That is currently blocked on an implementation of it inside `drm-rs` (discussed [here](https://github.com/Smithay/drm-rs/issues/25#issuecomment-515692555)), which I want to tackle in the upcoming weeks.

So the plan is currently:
[ ] implement atomic-modesetting in drm-rs
[ ] implement an atomic-modesetting based renderer in smithay (this will not deprecate the old one, which remains useful)
[ ] implement support for planes
[ ] fixup my nvidia branch (which *should* just work at this point)
[ ] (maybe try to support the old renderer as well, but I have no seen any nvidia cards supporting EGLStreams, but not atomic-modesetting yet, so why bother)
