### ISSUE TITLE
`wlr_layer`'s `pre_commit_hook` can post an error, disconnecting the client, leading to a panic later on in the `commit` handling

### ISSUE THREAD

**Issue by LogicalOverflow** [Smithay/smithay#1407]
While running wlcs tests (namely `LayerSurfaceTest.specifying_zero_size_without_anchors_is_an_error`) against [Pinnacle](https://github.com/pinnacle-comp/pinnacle), I ran across a panic in smithay.

The root cause is that the test requests a zero-width window without anchors, causing the `pre_commit_hook` in `wlr_layer` to (correctly) signal a protocol error for the surface, disconnecting the client:
https://github.com/Smithay/smithay/blob/7544c4d4b9ef89e2945bb626dd47518fedc5f660/src/wayland/shell/wlr_layer/handlers.rs#L132-L138

The panic then occurs in `commit` function for `PrivateSurfaceData` when `unwrap`ing the surface's client here:
https://github.com/Smithay/smithay/blob/7544c4d4b9ef89e2945bb626dd47518fedc5f660/src/wayland/compositor/tree.rs#L292

My first intuition for a solution would be to cleanly handling the case, that `client()` returns `None`, cleanly in the `commit` function, but I am not sure what exactly that entails.

For reference, the panic in the wlcs test output looks like this, but that's only marginally helpful: https://gist.github.com/LogicalOverflow/804f83c870da2a7667fb9f6d3d915043#file-pinnacle-wlcs-log-L449

(https://github.com/pinnacle-comp/pinnacle/pull/204 to make this issue show up in there)

**Comment by Drakulix** [comment]
> My first intuition for a solution would be to cleanly handling the case, that client() returns None, cleanly in the commit function, but I am not sure what exactly that entails.

I think we need to one step higher in the backtrace here. If the client has since disconnected, we probably shouldn't go into `commit` anyway, as the surface is effectively dead.

But I am pretty certain not unwrapping and simply returning would probably already work, as commit is directly called from the request-handler.

**Comment by LogicalOverflow** [comment]
> I think we need to one step higher in the backtrace here. If the client has since disconnected, we probably shouldn't go into commit anyway, as the surface is effectively dead.

That sounds like the cleaner solution. Same probably goes for all `pre_commit_hook`s, i.e. not calling them if the surface dies before it is invoked, then everyone can safely assume "When I get called, the surface is alive". 

Would a `surface.is_alive()` call be the right way to check this? If so, I'd be happy to make a PR to fix this.

**Comment by Drakulix** [comment]
> Would a `surface.is_alive()` call be the right way to check this? If so, I'd be happy to make a PR to fix this.

Yes, that should be sufficient.

**Comment by LogicalOverflow** [comment]
I have tried implementing this, and `surface.is_alive()` isn't enough here: After `post_error` only the client gets disconnected, but the surface continues to return true for `is_alive`, because its `object_info` is not removed yet.

To actually notice, that the surface is effectively dead I need to not only check if the `object_info` exists (as `is_alive` does), but also if it has a client id, that also has associated client data. This is (I think) pretty close to what a call to `client()` does anyways.

The solutions I see are:
- check both `is_alive()` and `client().is_some()` before calling into `commit` or `pre_commit_hooks`
- check only `is_alive()` and don't `unwrap()` in `commit`
- just don't unwrap `unwrap()` in `commit`
- do more on `post_error`, like cleaning up the surface such that `is_alive()` returns false after it. No idea if that is a reasonable thing to do, or if that should happen in smithay or wayland-server

**Comment by Drakulix** [comment]
> do more on post_error, like cleaning up the surface such that is_alive() returns false after it. No idea if that is a reasonable thing to do, or if that should happen in smithay or wayland-server

I don't think it is, given that more requests might still be in-flight, I think it is best to process them normally until wayland-rs handles the disconnect. (Which probably happens right after processing all pending events.)

So this means, we probably just need to be more defensive when calling `client()` and don't assume it will always succeed, just because `is_alive` returns true.

This assumption is likely a problem for other parts of the code-base, in case you feel like grep-ing for `client()` calls and fixing them as well.

For the problem at hand though, I think just not `unwrap`-ing and returning early, if there is no client, is sufficient.
