### ISSUE TITLE
WebAssembly/WebGL

### ISSUE THREAD

**Issue by Immortalin** [Smithay/smithay#213]
I am trying to build a more modern version of Xpra, how difficult would it be to modify anvil to use WebGL (i.e. wgpu) instead of glium?

**Comment by Drakulix** [comment]
I feel like this short question mixes multiple problems/questions into one and simplifies it a bit.
Let me try to explain/answer this:

## 1. How difficult would it be to modify anvil to use `wgpu-rs` instead of `glium`?

wgpu is just build upon gfx-hal, which uses vulkan/dx11_12/metal/opengl.
We currently have no vulkan support, but if the OpenGL backend is already capable enough, you would *only* need to touch the context creation.

As far as I know it would be enough to adjust [this file](https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/window/glutin.rs) of `gfx-backend-gl` to use our `winit` or `gbm` backend.
I believe this can be done out of tree without forking and I would love to support gfx-hal.

After that gfx-hal and therefor wgpu *should* just work. But smithay would still render a desktop environment directly to a display or a window. Also note there is no WebGL involved in any of this. `wgpu` is just modelled after WebGPU (not WebGL), which means they share a similar api, nothing more.


## 2. How difficult would it be to compile smithay to WebAssembly and run it in the browser.

That is a much different more complex question.
First of all, you cannot simply compile smithay to WebAssembly and expect it to just work. We probably have dependencies, that are WebAssembly incompatible, but most importantly, while we have a pure-rust version of wayland-rs/wayland-server, that tool expects to listen on a UnixSocket natively on the system.

A WebAssembly program cannot do this without runtime support, which no browser will ever offer. This might work in something like `wasmtime`, but the next big problem then is rendering.

It seems you want to render processes in the browser using WebGL? Lets explore that in another question, but for hardware-acceleration you need a native GL-context on the GPU. It can be a headless one (so no window or monitor setup involved), but this again will require WebAssembly runtime support. So you probably want to do all of this with a native executable.

Also since you will render on the GPU, you will need to read-out the result and stream it somewhere to be displayed (e.g. a browser), which sounds a lot like Xpra, which captures windows from a headless Xorg instance and streams them via H264 video.


## 3. How difficult would it be to build something like Xpra in smithay.

Lets take away all the Web-stuff for a moment.
To build something like Xpra you need to be a wayland-server, render buffers and send them somewhere. This is easy for shm-buffers, but they are not hardware-accelerated, which means clients could not do GL or Vulkan for example.

For GL/Vulkan-clients to work, you need a headless context, which should be easy to hack together with our winit-backend. But requires *some* work.

Streaming is something you would need to figure out on your own. Displaying those streams can then basically happen everywhere. Even in the browser or in another wayland-server, because you would just display video, capture input events and send them back to smithay.


## 4. How difficult would it be to render smithay in browser with WebGL.

If you have build something like the tool outlined in *3.* you can render any window or a complete DE in smithay and display then where you like. You can also just render the windows in smithay and use WebGL to composite them client-side. Smithay is not really involved in this.

If you would compile smithay to WebAssembly, figure out how to connect other webassembly clients (maybe via websockets) and render them in the browser, then you could also just use WebGL. In that case no hardware acceleration beyond WebGL is possible anyway, so you would only render SHM-Buffers, which are just bitmaps or figure out a custom-webgl-protocol, which would be quite difficult. (Like the whole not terribly useful approach).

But I guess the later is not your goal. If it is however there is [Greenfield](https://github.com/udevbe/greenfield), which does run completely in the browser and has support for web-clients.

I guess you could re-implement Greenfield in Rust, if you feel like, but you would likely need to modify a lot of code of smithay. Greenfield also has a custom H264 buffer protocol and can render native clients, via a remote-native-binary. That binary could also be done via smithay and is essential the core of the idea outlined in *2.*.


I hope this was helpful. If you could specify what exactly you wanna build out of wgpu/WebGL/WebGPU and smithay I could give you much more directed feedback.
