### ISSUE TITLE
[Anvil] Locking / Repeating input when keys pressed

### ISSUE THREAD

**Issue by adamijak** [Smithay/smithay#242]
I tested this on weston terminal and alacritty, with same result.

## Issue

Press modkey + '1' or '1' + modkey and it starts to keep repeating '1'. It behaves like '1' was never released.

## Environment

- tty has issue
- winit not tested yet

**Comment by vberger** [comment]
Was it running anvil on a tty, or using the winit backend ?

**Comment by adamijak** [comment]
@vberger edited

**Comment by PopeRigby** [comment]
I think I'm having a related issue. When I run Anvil with winit, unfocusing and then focusing it makes it behave like Mod4 is still pressed when I focus again. I think this is because both the Sway and Anvil modifier key are Mod4, so Mod4 will always be pressed when I unfocus Anvil.

**Comment by cmeissl** [comment]
Tested with `weston-terminal` on `anvil --tty-udev`.
I can not reproduce the issue when pressing `modkey + 1`, but pressing `1 + modkey` and then releasing `1` will trigger this issue.

Here is the relevant part from the `WAYLAND_DEBUG` output of `weston-terminal`:

```
[1339612.703] wl_keyboard@17.key(1531, 7153812, 2, 1)
...
[1340590.582] wl_keyboard@17.key(1532, 7154791, 125, 1)
...
[1342183.792] wl_keyboard@17.key(1534, 7156386, 125, 0)
```

The release of `1` is indeed missing.

A trace log of `anvil` reveals that the key press is sent to the client, but the release is intercepted by the keyboard shortcut [filter](https://github.com/Smithay/smithay/blob/f9f77288c8861d80a57b9fe32af85c9efb104d77/anvil/src/input_handler.rs)
The release will be processed as a [screen](https://github.com/Smithay/smithay/blob/f9f77288c8861d80a57b9fe32af85c9efb104d77/anvil/src/input_handler.rs) action.
Because the filter returns false the keyboard handler will [not forward the call](https://github.com/Smithay/smithay/blob/f9f77288c8861d80a57b9fe32af85c9efb104d77/src/wayland/seat/keyboard.rs) to the client.

Anvil log for key press:

```
Jun 17 21:51:54.735 DEBG key, state: Pressed, keycode: 2
Jun 17 21:51:54.735 TRCE Handling keystroke, state: Pressed, keycode: 2, smithay_module: xkbcommon_handler, seat_name: seat0, smithay_module: seat_handler
Jun 17 21:51:54.735 TRCE Calling input filter, sym: 1, mods_state: ModifiersState { ctrl: false, alt: false, shift: false, caps_lock: false, logo: false, num_lock: false }, smithay_module: xkbcommon_handler, seat_name: seat0, smithay_module: seat_handler
Jun 17 21:51:54.736 DEBG keysym, keysym: 1, mods: ModifiersState { ctrl: false, alt: false, shift: false, caps_lock: false, logo: false, num_lock: false }, state: Pressed
Jun 17 21:51:54.736 TRCE Input forwarded to client, smithay_module: xkbcommon_handler, seat_name: seat0, smithay_module: seat_handler
```

And here the release is not forwarded:

```
Jun 17 21:51:57.133 DEBG key, state: Released, keycode: 2
Jun 17 21:51:57.133 TRCE Handling keystroke, state: Released, keycode: 2, smithay_module: xkbcommon_handler, seat_name: seat0, smithay_module: seat_handler
Jun 17 21:51:57.134 TRCE Calling input filter, sym: 1, mods_state: ModifiersState { ctrl: false, alt: false, shift: false, caps_lock: false, logo: true, num_lock: false }, smithay_module: xkbcommon_handler, seat_name: seat0, smithay_module: seat_handler
Jun 17 21:51:57.134 DEBG keysym, keysym: 1, mods: ModifiersState { ctrl: false, alt: false, shift: false, caps_lock: false, logo: true, num_lock: false }, state: Released
Jun 17 21:51:57.134 TRCE Input was intercepted by filter, smithay_module: xkbcommon_handler, seat_name: seat0, smithay_module: seat_handler
```
