### ISSUE TITLE
Xwayland API is fundamentally broken

### ISSUE THREAD

**Issue by psychon** [Smithay/smithay#245]
Sorry for the title. Feel free to edit this. ;-)

I've been trying to get `Xwayland` to work. The latest issue is this one (after `Xwayland` started successfully):
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', [snip]/smithay/src/xwayland/xserver.rs:182:48
```
That line number points here:
https://github.com/Smithay/smithay/blob/36e11284c27c452557f8eb7799060c0b8e6a3ea7/src/xwayland/xserver.rs#L177-L179

I certainly do not understand this, but Levanx seems to do:
```
<Levanx> the `client_destroy::<WM, T>(&e, data.get().unwrap())` is a deeper problem though
<Levanx> I missed an important assumption when I wrote this code, and the automatic-restart of XWayland just cannot work like this
<Levanx> We'll need to change the API, probably by making the compositor process restart xwayland, rather than having it restart automatically
```

**Comment by vberger** [comment]
More details : the current XWayaland machinery tries to restart XWayland from the wl_client destructor, but it is not possible because at this point it does not have access to the dispatch data, making this unwrap explode.

To solve this, we should probably consider the XWayland machinery to only report to the user that XWayland died, and let the user restart it.
