### ISSUE TITLE
XDG shell move stops working after resize

### ISSUE THREAD

**Issue by PolyMeilex** [Smithay/smithay#321]
I'm not 100% sure, but it seems that it is impossible (or maybe just hard) to reproduce this when checking out commits before #286 

Steps to reproduce:
1. Start a client (nautilus in my case, it seems that it's a lot harder to reproduce with some clients, like terminals, no idea why)
2. Resize it
3. Try to move it
4. This will produce this kind of behavior: 
![gif](https://i.imgur.com/5fKf1zU.gif)

**Comment by cmeissl** [comment]
Hm, my first guess would be that something is wrong with the serials. I will check.

**Comment by cmeissl** [comment]
So, the issue is that [this line](https://github.com/Smithay/smithay/blob/5cfb05cde80bab40f6e7735be474d078474f060b/anvil/src/shell.rs#L462) does not evaluate to true because we are waiting for a configure that has the state `Resizing` but the configure will never have this state cause we remove it when we stop resizing. 
If we want to keep the resize logic as is we could instead check the current state of the toplevel which will still have to the state `Resizing` because the current state will be set on the next commit after `AckConfigure` was processed.
