### ISSUE TITLE
How does smithay differ to wlroots and other questions

### ISSUE THREAD

**Issue by Joe23232** [Smithay/smithay#397]
Hi I have some questions.

1. How does `smithay` compare to `wlroots`. Which one would be more difficult to use (pretending that `smithay` is ready)?
2. There is this tiling window manager for wayland called [`dwl`](https://github.com/djpohly/dwl). Does anyone happen to know if there are any similar tiling window managers using `smithay` which adheres to suckless's philosophy in terms of how you configure everything via source code?
3. Are there any taskbars or widgets that are using `smithay`?

**Comment by PolyMeilex** [comment]
1. wlroots is more abstracted, so I would say it's easier, as long as you have decent C knowledge
3. It's not smithay's job, it is a compositor/sever toolkit so smithay-client-toolkit is probably what you are asking about, I believe there are some projects that use it for taskbars

**Comment by PolyMeilex** [comment]
> Sorry mate what is not `smithay`'s job?

Smithay is used to build Wayland compositors / the server itself 
Some may want to hardcore bar into that, but  when you say taskbars my guess is that you mean something like i3bar or polybar, where a bar is a client rather than being build into compositor, in this case smithay-client-toolkit should be used, or gtk, or any other client toolkit of your choice
