### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by Drakulix** [Smithay/smithay#4]
Hey @vberger,

I want to take part in smithay's development.
I would like to know what's to do, where I can help. :)

I would like to start looking into rendering possibly with `glutin` at first to have a more easy target. And nested rendering would most likely be very useful for testing, before I start to explore `libdrm` and sorts, but I am not sure if there is a lot to do in that direction, when there is not a lot to render.

I am basically searching for some easy entry points into contributing.

The final goal will of course be to move `fireplace` over to `smithay`, but that will of course take some time. ^^

Greetings,
Drakulix

**Comment by vberger** [comment]
Hey !

I must admit I'm quite glad to see your interest !

First of all, what will you be doing with `fireplace` in the meantime? It looks like a very nice project, I really hope you won't be completely putting it to sleep for months waiting for `smithay` to reach the feature-level of wlc...

That said, as you can see there is a lot to do ! I just finished the SHM helpers, which is to be honest a quite fundamental and "basic" functionality (as in, it is implemented in the wayland-server.so lib and WLC used that, but because of my design I could not reuse it.. and it proved not that easy to design properly!).

For the rest, I am still quite at the "how should we design this?" point. I'm not opposed to iterative design and refactoring along the way as we understand better the constraints, but I'm willing to take some time thinking to start with a not-too-stupid design.

For now, I see two big categories of potential modules:

- helpers to handle the wayland protocol(s), oriented to processing client requests (like the `shm` module)
- helpers to handle the backend of the compositor (be it X11, an other compositor, or directly a VT)

For the first part, this is still very nebulous for me.

Regarding the second, I guess it's basically a "multiple backends" situation. That would probably fit into a big `Backend` trait (to allow easy genericity). In this case, a glutin+glium backend seems indeed like a good starting point for quickly having something that works!

Right now, I don't have much more details in my head to be honest. You can look at the API I designed for the SHM helpers on [the API docs of smithay](https://vberger.github.io/smithay/smithay/index.html). I'd love to have your feedback on it. :)

If you're willing to discuss in a more instantaneous way, I have [matrix](https://matrix.org) room dedicated to my wayland projets (for now there's mostly github/travis bots that spam, but I hope it'll change ^^): https://matrix.to/#/#smithay:safaradeg.net . I can probably make it bridged to an IRC channel on mozilla's IRC server, if you prefer.

Welcome in this adventurous boat!
Victor

**Comment by Drakulix** [comment]
> First of all, what will you be doing with fireplace in the meantime? It looks like a very nice project, I really hope you won't be completely putting it to sleep for months waiting for smithay to reach the feature-level of wlc...

I will continue developing it based on `wlc`. I still have enough stuff to develop and I think that the transition, when it finally happens, will be relatively easy.

You might have taken a look at how the whole think works, basically everything is based on this single [`Trait`](https://drakulix.github.io/wlc.rs/wlc/trait.Callback.html). I hope to replace all implementations of this trait with implementations for the appropriate handlers.

And in the meantime I will hopefully be able to patch `wlc` to the point where it works with most wayland clients I need - although winit already does not work, which will be annoying, when targeting glutin - to continue to run fireplace (in the worst case I still have XWayland).

This is not the best news, so lets just hope, that progress will be fast enough :grinning: 

> For the first part, this is still very nebulous for me.

For me as well, maybe we should start at the other end and think about how we would like to use the library. You already started with some very good thoughts, but maybe I can provide some more specific input though my experience with the wlc protocol? Do you think this is a good idea or do you want to start fresh?

> That would probably fit into a big Backend trait (to allow easy genericity). In this case, a glutin+glium backend seems indeed like a good starting point for quickly having something that works!

So then the first step would most likely be to design the `Backend` trait? You most likely have a better idea, what is required for wayland to render and receive input.

**Comment by Drakulix** [comment]
Oh an about matrix.

The only chat software I used for github projects recently was gitter, but I have really no strong preference. If you like matrix, I will set that up and I am fine with that. I am just generally much more used to manage my projects in issues and also prefer that for a better overview of past conversation.

But as I said, what ever you wanna use for your project.

**Comment by vberger** [comment]
I'd definitely love to have your insights about your experience of the wlc protocol. What is good about it? What isn't? My main flaw here is clearly that, given I've never worked on a compositor, I don't have a clear view of what functionality is needed and what is more secondary...

Regarding the chat, it's not an hard requirement, I'm fine with exchanging on github issues. And if you prefer gitter, I believe there is a matrix<->gitter bridge I can setup. 😉

**Comment by vberger** [comment]
> So then the first step would most likely be to design the `Backend` trait? You most likely have a better idea, what is required for wayland to render and receive input.

This is indeed a step we'll need to do relatively quickly. And It'll mean deciding how low-level we want it. (My personal opinion would be the thinnest possible abstraction layer over the various potential backends).

From what I see, there are two main part of defining the backend:

- graphics part (how the compositor draws to the screen)
- input part (how the compositor receives mouse/keyboard/etc...)

Now, I can see 4 potential backends:

- glutin: probably the one that we could get working the fastest, but it'll be quite crippled from the input point of view, as glutin preprocesses inputs a lot and forces its event-loop on us
- raw X11: I know nothing about how it works :)
- raw wayland: the compositor is basically a wayland client, should not be too difficult to setup on top of `wayland-client`
- raw TTY: we initialize an OpenGL context on a TTY and use libinput to retrieve user input. It is blocked on https://github.com/vberger/wayland-client-rs/issues/83 for integrating libinput on the event-loop

**Comment by Drakulix** [comment]
I would actually really want to drive the glutin backend forward. Not only would this keep us from dealing with X11 and Wayland directly and avoid too much code duplication, but it would also provide the option to *potentially* run this on other more experimental platforms like Android or Windows 10's bash environment.

It's event loop could of course be quite problematic, but that's something we will likely face with other backend's as well, basically any GUI framework.

Maybe we can push some input additions to the library, I think alacritty is already using a fork for more raw input handling and is trying to upstream these changes?

I also don't have a lot knowledge about writing a raw X11 backend, but I think that's rather low in priority anyways.

I will try to wrap up my insights on wlc's api tomorrow, when I have some more time for that.

**Comment by Timidger** [comment]
>I'd definitely love to have your insights about your experience of the wlc protocol. What is good about it? What isn't? My main flaw here is clearly that, given I've never worked on a compositor, I don't have a clear view of what functionality is needed and what is more secondary...

@vberger Just to chime in, there are quite a few issues I personally have with wlc:

* Assumes single threaded access, which coupled with their immediate api made it very easy to have data races in C (even with a single thread) and very easy to have a deadlock/dropped action when using a Read Write Lock (which is what Way Cooler mostly uses).
* _Very_ bad rendering system, because of the immediate api and lack of caching any action causes a redraw (just load up any wlc-powered window manager that draws e.g borders and wiggle the mouse. You'll notice your CPU usage jump up...).
* Bad code base. It was overly abstracted, and used custom libraries that cloudef used. That, coupled with a lack of documentation, made it hard to hack on. Having good documentation for this project would be a huge help for people wanting to contribute.

Some things it did do nicely:
* Had an example that was short and easy to understand. It may have been poorly designed, but it was very easy to get into.
* Managed enough things that the compositor didn't always have to re-implement it (e.g xdg-shell). This is a double edge sword though, wlc had a very rough patch when it was between versions of xdg-shell which it only recently has fixed.
* Maintained. This of course changed when Sway announced they are switching away from it. The project doesn't necessarily need a big name behind it, just a healthy amount of contributors.

Good luck with this project guys, I'm going to keep an eye on it for sure. I'm going to try to work with the Sway compositor framework, but if this goes really, really well / Sway's compositor doesn't line up with Way Cooler's interest I'll look into this project.

**Comment by vberger** [comment]
@Drakulix Actually, the "event loop" part of glutin is probably not that bad: we can always move it to an other thread so that it does not lock the other compositor's jobs.

The input part worries me more: regarding keyboard handling, we'll need to use libxkbcommon in all cases (because the state sent to the clients with modifier keys must be serialized by it). I hope glutin does not lose too much information. Alacritty's needs are slightly less general, they need to get the modifier's keys state, while libxkbcommon needs to keep track of the whole keyboard state.

I guess a first step regarding this will be to make proper rust bindings for libxkbcommon.

@Timidger Thanks a lot for your input! This confirms some of my first ideas about how to handle this. From the start, I've made a point to have wayland-client and wayland-server threadsafe. So I very well intend smithay to be threadsafe as well!

The documentation point you raise is indeed very important too. I have the feeling it's a common issue with wayland... `libwayland-client` and `libwayland-server` documentations are quite minimalistic too. I can't count the number of time I had to just go read the code of the lib to understand how it should be used...

About where to draw the limit of what's smithay job and what isn't, I'm partisan of starting small and building. First, only provide the lowest-level abstractions, that basically any compositor could need, and then build on that to provide more abstracted structures as some patterns emerge (but still expose the low parts, if anyone wants to use them).

In this vein @Drakulix : I believe the `Backend` trait should be very minimalistic too: basically it should provide an API for getting inputs (requiring to be given an `Handler` maybe?) and provide an OpenGL context & surface. Probably some secondary stuff (like supporting the underlying display to be resized, for software backends), but that should be it.

**Comment by vberger** [comment]
I'll start digging into `libinput`'s API. I'm willing to use it as a starting point to conceive the input part of `Backend`.

**Comment by Drakulix** [comment]
Thoughts about **wlc**:

The best thing about wlc, is the abstraction of `Output`s and `View`s. Most of the time, you are only dealing with application windows and something to render them on. You usually don't care that much, if it is a normal window, a popup or a something completely different for most operations. And if you do, you can access *most* of the properties easily.

*Most* marks the biggest problem wlc has in my eyes in API design. It abstracts too much *away*.
Writing a wayland compositor you are also writing an X window manager, if you support XWayland. Which means you need to access a bunch of information of the underlying window. A very prominent example of something missing in wlc, the hints for client side window decorations.

While in wayland just everything uses CSD, GTK actually does as well in X, but most frameworks do not. Without reading out the required hint, you can either draw a border for all X windows or for non. wlc's abstraction even gets so far, that it is quite difficult to figure out, if you are dealing with an X-Client or not.

Similar things can be said about a lot of types in wlc. And others things like the annoying xdg-positioner api, which should be handled identically in all compositors, is not abstracted away, but instead directly exposed in the API.

Another big problem is, that wlc insists of doing the rendering for you. You can draw stuff *around* or over the Views, but you cannot control the Views themselves, e.g. for window previews or animations or ... or ... Basically you cannot have any nice effects like this.

>  Very bad rendering system, because of the immediate api and lack of caching any action causes a redraw (just load up any wlc-powered window manager that draws e.g borders and wiggle the mouse. You'll notice your CPU usage jump up...).

Actually that is not true. The CPU-usage will go up, because the only real API it provides copies raw pixel/bitmap data into and from a texture and renders that onto the framebuffer. That copy operation will use most of your CPU, if done very frequently.

But if you actually do OpenGL rendering in the provided hooks (and make sure you reset to the old state after rendering, something we will not have to worry about with `glium`, which is incredibly awesome), it is very fast. @Timidger Test fireplace, you will see no noticable increase, I am doing all my rendering in GL (which was very easy to do with `piston2d-graphics` and `conrod`).

So basically we should abstract all common problems away. But there should always be a way to access all underlying parts, at best in combinations with all common abstractions.

About the other things mentioned:

> Assumes single threaded access, which coupled with their immediate api made it very easy to have data races in C (even with a single thread) and very easy to have a deadlock/dropped action when using a Read Write Lock (which is what Way Cooler mostly uses).

This is a big problem, absolutely right.

> The input part worries me more: regarding keyboard handling, we'll need to use libxkbcommon in all cases (because the state sent to the clients with modifier keys must be serialized by it). I hope glutin does not lose too much information. Alacritty's needs are slightly less general, they need to get the modifier's keys state, while libxkbcommon needs to keep track of the whole keyboard state.

> I'll start digging into libinput's API. I'm willing to use it as a starting point to conceive the input part of Backend.

Do we need libxkbcommon bindings? wlc can also use libinput running nested in X, less input backends the better, right?

> libwayland-client and libwayland-server documentations are quite minimalistic too. I can't count the number of time I had to just go read the code of the lib to understand how it should be used...

This is btw not much better, when using you libraries and not knowing the original C libraries very well. :smile: 

> I believe the Backend trait should be very minimalistic too: basically it should provide an API for getting inputs (requiring to be given an Handler maybe?) and provide an OpenGL context & surface. Probably some secondary stuff (like supporting the underlying display to be resized, for software backends), but that should be it.

I believe this as well. But I want to propose splitting `Backend` into two traits. `RenderBackend` and `InputBackend` and make it possible to use multiple `RenderBackend`s in parallel providing outputs to render on.

I think this will help with dealing with multiple graphic cards as well as allowing some more crazy backends. E.g. one could create virtual outputs with headless contexts and then capture those. For example to plug the rendered screens into ffmpeg and stream them to a chromecast or similar.

I think we should not combine rendering and input, where it actually does not belong, there are just more common combinations. We can then also use glutin for running the compositor nested, but still use libxkbcommon or libinput, *and* we could even switch between the two, if we support both.

**Comment by vberger** [comment]
> A very prominent example of something missing in wlc, the hints for client side window decorations.

This is actually a lack at the protocol level, I've ran into this too, with `wayland-window`. The situation is comically sad actually: Gnome and KDE do not agree on decorations. Gnome's compositor will expect client-side decorations, while KDE's will draw server-side decoration. And XDG-shell does not contain a decoration negotiation mechanism...

However KDE seems to have made a protocol extension for it : https://github.com/KDE/kwayland/blob/master/src/client/protocols/server-decoration.xml

Regarding libxkbcommon, it is not required to retrieve the events from hardware, but actually to send them to the clients, so yeah, we'll need it no matter what (and it also nicely abstract for us the keymap handling, so I'm really in favor of using it).

It makes sens to split the input and render part of the backend, you are right. We'll just need to be aware that not all combinations of render/input backends are possible. And probably various init methods will provide a pair of backends. I can imagine for example a

```rust
fn init_glutin_backend() -> (GlutinRenderBackend, GlutinInputBackend) { ... }
```

Regarding documentation, I've started writing a [rusty wayland book](http://vberger.github.io/wayland-client-rs/book/intro.html). It's still very WIP, but I plan to write here all I understood about the wayland protocol itself, and the details on how my `wayland-client` and `wayland-server` crates are to be used. Any feedback and contributions on it are welcome 😉 , it's hosted in [wayland-client-rs](https://github.com/vberger/wayland-client-rs/tree/master/book) repository.

**Comment by Drakulix** [comment]
> This is actually a lack at the protocol level, I've ran into this too, with wayland-window. The situation is comically sad actually: Gnome and KDE do not agree on decorations. Gnome's compositor will expect client-side decorations, while KDE's will draw server-side decoration. And XDG-shell does not contain a decoration negotiation mechanism...

So this will continue to happen on wayland, great...
Well the default behavior seems to be to have CSD, so the KDE protocol should probably be implemented for those, that which not to have/want CSD.

> Regarding libxkbcommon, it is not required to retrieve the events from hardware, but actually to send them to the clients, so yeah, we'll need it no matter what (and it also nicely abstract for us the keymap handling, so I'm really in favor of using it).

Already then I am going to start looking into writing bindings for that soon.

> We'll just need to be aware that not all combinations of render/input backends are possible. And probably various init methods will provide a pair of backends.

I would say we should enable all combinations, that are possible to initialize. A lot of init functions will not only return a pair, but a `Result` and just not work in the context the compositor is launched. Once a backend can be loaded, it should return something usable, so that problem will hopefully go away.

>  Regarding documentation, I've started writing a rusty wayland book. It's still very WIP, but I plan to write here all I understood about the wayland protocol itself, and the details on how my wayland-client and wayland-server crates are to be used. Any feedback and contributions on it are welcome :wink: , it's hosted in wayland-client-rs repository.

I don't have a lot knowledge to provide for the book right now, but this is great news!

**Comment by Drakulix** [comment]
Leaving this here: https://github.com/rtbo/xkbcommon-rs

At worst this a good base to fork.

**Comment by vberger** [comment]
That's a good starting point indeed! Do you know if it's still maintained?

**Comment by Drakulix** [comment]
> That's a good starting point indeed! Do you know if it's still maintained?

I don't and there does not seem to be much activity on the repository, but I remembered I am actually using those bindings in my wlc bindings, although mostly for the keysyms:
http://rtbo.github.io/xkbcommon-rs/xkbcommon/xkb/keysyms/index.html

So at least it compiles. I would say we go with it until we hit a bug and then discuss, if we should fork it or replace it with some fresh bindings.

**Comment by vberger** [comment]
Yep, keeping in mind that the xkbcommon logic is mostly useful for serializing keyboard state to the clients, so it'll probably belong in some logic to handle `wl_seat` and its friends.

This is completely orthogonal to the Backend traits... I'll open a few other issues to organise the discussions on topics

**Comment by Drakulix** [comment]
For the overall plan, what would you suggest as the next step on my end? I was thinking about starting to work on `libinput` and `drm` backends now.

**Comment by vberger** [comment]
If you're willing to dig into that, sure, go for it !

I think I'll try to tackle libxkbcommon and the `wl_seat` handlers. With that and the shm buffers, we'll be able to start making a toy compositor and simple apps.

**Comment by Drakulix** [comment]
https://github.com/Drakulix/input.rs

**Comment by vberger** [comment]
So, let's not let it sink, shall we ? 😁 

Sorry for the lack of activity on my side during the last 10 days, I've had various personal matters to take care of.. Everything should be settled in a few days though. :)

**Comment by Drakulix** [comment]
Well **I** did not let it sink ^^

https://github.com/Drakulix/input.rs/commits/master

The bindings are almost done. I expect to start on implementing the InputBackend for them sometime next week and to open a pull request shortly after :)

**Comment by Drakulix** [comment]
Just a quick heads up.

As of https://github.com/Drakulix/input.rs/commit/6f39a8c36c207da2f9beeb9b6e482396aca66722 the bindings are done, but I am taking some additional time to clean up the code, fix some inconsistencies and add documentation, because I will probably not be motivated, once I start on smithay again to do this later.

So some more days to go.

**Comment by Drakulix** [comment]
https://github.com/Drakulix/gbm.rs ...

At least
https://github.com/rust-kms/libdrm-rs/
and https://github.com/Nercury/egli-rs/

look feature complete and usable.

**Comment by vberger** [comment]
I'll close this, as the plan of the project is now mostly set :sweat_smile:
