### ISSUE TITLE
Should we implement CompositorToken with Send trait?

### ISSUE THREAD

**Issue by fangyuanziti** [Smithay/smithay#66]
In my situation, I want to access the `CompositorToken` in multiple threads. The smithay's document indicates it should be sendable while the fact is not. Is the wayland c library already thread safe for this? Should we implement `CompositorToken` with `Send` trait?

**Comment by vberger** [comment]
`CompositorToken` was `Send` previously, but it is no longer as the `EventLoop` from wayland-server is no longer `Send + Sync`.

It appeared that having it `Send + Sync` was potentially an error, and in any case making things more complicated than necessary regarding implementation (it forced all values of the `StateStore` to be `Send` as well, which poses issues with the implementation of the system backends).

However, this need not be a final state, I'd be glad to improve wayland-server in consequence to gracefully allow both `Send` and non-`Send` `EventLoop`s, once I find an appropriate design for this.

The deep issue for me is that the C library is not very clear about which actions are actually thread-safe and which are not...

Could you explain briefly why you need the `CompositorToken` to be `Send` ? This would help me to have a rough idea of what you want to do, in order to rethink the design in consequence. Though I cannot guarantee you a solution will be found quickly...

**Comment by fangyuanziti** [comment]
I am working on a Wayland compositor which exposing a HTTP api.
I use `simithay` for compositor and `actix-web`(a rust web framework) for HTTP server.
The both library has it's own event loop which i can not merge them easily. So I run them in separated threads instead.
The problem here is how to  get `buffer` content of `surface` in HTTP thread (by `CompositorToken`).

**Comment by vberger** [comment]
I see thanks.

I'll try to see if/how this can be done. Though this will need to wait a few days, I'm quite loaded currently.
